travis:
  secure:
    BINSTAR_TOKEN: edSOSvLPIdaO2ZkgWKA0tAos0xQ1ZuvYNk7gZOGidhE1tiiB9YltJRqu43UpNx8pV8aoR3zGosLJnmVdITy1G3Wej23fjrcvROclX8QfudQrYCF9eyT+lvGKdK+UfzSAMpSn19HLuRFwSZJutscOjN117YCaLQuPIpgAnugYhChdaJSLX1pM17Y6YcfxMCPmdufP4ljlJAOMBgn6tkGnvBGgyijv17CzKHgQEMvoop5aUF9FtBp8DPwun5f2Kk3Q3ZrjfpTT+QQQohEut9i8e9wcfDestpTZb/AOUf8C0tQ720pXeTPrZhMrAQJ6l4LJx3TtyZkp9rYQY+0XIz3QSfWWMH/oCrv51fnMwV0JVfp6HauY3XQPYo0SoxTstpPR2SbrLw4tI0kv5SARCVyRKpV5lp+vgeOJuLGAZeq2Adb8JkbPKNV/itgTi/Jrlc4tCtByB280GoTahhUdtT44EiaBnNfnWpkhxj93uu7uZok8SeaQ7cECc+nwInXCx+vcXFIVsyLDuwc4+hSS0zUCSA/rppdedYTwY2XanXmM+hIbsV2WjCAKZBkFJ4FGAutsccGyzHPVZKZUB51iC8S5ZnZ4pvOIAmhV60af0fzIMlsVyjn7SG8KSmFFDI6cB/zOq2IXcLfNT50zi0A2RkBXegkm2m7u4Z+N2SnPzpjDrXc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
